### ISSUE TITLE
[USER ISSUE] Docker image pull failing

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#1939]
**Describe the bug**
Using Web UI / command line to pull custom docker images fails, while running docker pull <docker image name> succeeds
**Codalab Information**
- *UUID of problem bundle (please don't delete)*: https://worksheets.codalab.org/bundles/0x426b03b5b8db47a9bafead08fbdb52f8/
- *Error message received from Codalab (if applicable)*:
`Failed to download Docker image: Unable to find image: pytorch/pytorch:0.4.1-cuda9-cudnn7-devel from Docker HTTP API V2.`

**To Reproduce**
Steps to reproduce the behavior :
1. Use new UI to run a simple "date", fill pytorch/pytorch:0.4.1-cuda9-cudnn7-devel in docker image field
2. cl run 'date' --request-docker-image pytorch/pytorch:0.4.1-cuda9-cudnn7-devel

Both fails the bundle

Run locally: docker pull pytorch/pytorch:0.4.1-cuda9-cudnn7-devel
works

**Expected behavior**
Pull correct and run

**Comment by yipenghe** [comment]
#1924 maybe due to this update?

**Comment by teetone** [comment]
I also see this same issue with `tensorflow/tensorflow`.

**Comment by yipenghe** [comment]
Discussed on slack, need pagination

**Comment by yipenghe** [comment]
@candicegjing we probably should prioritize this

**Comment by moinnadeem** [comment]
Phew, I thought this was me. I spent my day debugging this; it wasn't able to replicate a macro due to it not being able to download the exact docker image that the macro ran; the macro never specified any particular image.

**Comment by yipenghe** [comment]
> Phew, I thought this was me. I spent my day debugging this; it wasn't able to replicate a macro due to it not being able to download the exact docker image that the macro ran; the macro never specified any particular image.

Sorry for the problem, I'm reviewing a PR that would fix this and we will make a new release asap

**Comment by yipenghe** [comment]
> Phew, I thought this was me. I spent my day debugging this; it wasn't able to replicate a macro due to it not being able to download the exact docker image that the macro ran; the macro never specified any particular image.

Actually, do you mind sharing your docker image if it's not sensitive? Would like to test that gets pulled too

**Comment by moinnadeem** [comment]
Can do! I will be back on a computer in 10 minutes.

**Comment by moinnadeem** [comment]
Sorry for the delay, and thanks for the help!

Bundle ID: 0x156d45a546b7439193ea82ec147ea707
Docker Image: codalab/default-cpu@sha256:ff7de716ac5f94d9b4ff8d6341d60166ed5b0163cc05d8d51da9418511caf5e1

Let me know if you need anything else from me. Happy to share any other details if they are needed.

**Comment by yipenghe** [comment]
> 0x156d45a546b7439193ea82ec147ea707

Are you trying to pull a specific docker image according to the sha commit? I don't think we support this. 

But I reruned the bundle with our default cpu image: codalab/default-cpu:latest , it successfully ran. If a bundle didn't specify a particular image, it was using our default images and in this case, if you hit "edit and rerun", the docker image field would be empty. It is safe to just use our default image (leaving the field empty) in this case

**Comment by moinnadeem** [comment]
Thanks for the quick reply!

I am not trying to do that; I'm trying to replicate the `dev-evaluation` macro from [this worksheet](https://worksheets.codalab.org/worksheets/0x859f79522f6548e3894695f2d9d6b5b6). If you look at bundle [ `0x2f26c4`](https://worksheets.codalab.org/bundles/0x2f26c41607da4313b0f97acd20bb093d), you'll see that it doesn't specify a docker image, and therefore, just runs with the latest one.

But when I use the macro on a [separate worksheet](https://worksheets.codalab.org/worksheets/0x3908d4e2e72e4c179e01e495551184a2), it adds in the docker image, which fails. 

Any clue why? I've been scratching my head at this

**Comment by yipenghe** [comment]
> Thanks for the quick reply!
> 
> I am not trying to do that; I'm trying to replicate the `dev-evaluation` macro from [this worksheet](https://worksheets.codalab.org/worksheets/0x859f79522f6548e3894695f2d9d6b5b6). If you look at bundle [ `0x2f26c4`](https://worksheets.codalab.org/bundles/0x2f26c41607da4313b0f97acd20bb093d), you'll see that it doesn't specify a docker image, and therefore, just runs with the latest one.
> 
> But when I use the macro on a [separate worksheet](https://worksheets.codalab.org/worksheets/0x3908d4e2e72e4c179e01e495551184a2), it adds in the docker image, which fails.
> 
> Any clue why? I've been scratching my head at this

Hmm, I don't see 0x2f26c4 on the separate worksheet. If you are trying to use the same bundle on a different worksheet, you can "edit source", and add []{0x2f26c4}, it would appear in the worksheet and would be referencing to the same bundle (0x2f26c4).

For 0x156d45, can you open a new github issue describing how you created this bundle? I think it's a different cause from this issue

**Comment by moinnadeem** [comment]
Sounds good! I'd also like to test if the fix you're about to release fixes it before you push the release, do you know when you plan to deploy it?

**Comment by moinnadeem** [comment]
Created #1942 to discuss the problem

**Comment by yipenghe** [comment]
> Sounds good! I'd also like to test if the fix you're about to release fixes it before you push the release, do you know when you plan to deploy it?

I'm not sure how test locally unless you clone the repo and checkout to the fix branch and build locally. However, if you have a particular image you wanna test, you can let me know

**Comment by moinnadeem** [comment]
> I'm not sure how test locally unless you clone the repo and checkout to the fix branch and build locally. However, if you have a particular image you wanna test, you can let me know

Oh, my apologies, I meant after you plan to deploy it.

ie. if you plan to deploy tonight, I would wait and test if it fixes things. If not, I can change tasks and try again when the fix has been deployed.

**Comment by yipenghe** [comment]
> > I'm not sure how test locally unless you clone the repo and checkout to the fix branch and build locally. However, if you have a particular image you wanna test, you can let me know
> 
> Oh, my apologies, I meant after you plan to deploy it.
> 
> ie. if you plan to deploy tonight, I would wait and test if it fixes things. If not, I can change tasks and try again when the fix has been deployed.

Ah I see, we plan to deploy later today or early tomorrow, but not sure the exact time

**Comment by yipenghe** [comment]
> > I'm not sure how test locally unless you clone the repo and checkout to the fix branch and build locally. However, if you have a particular image you wanna test, you can let me know
> 
> Oh, my apologies, I meant after you plan to deploy it.
> 
> ie. if you plan to deploy tonight, I would wait and test if it fixes things. If not, I can change tasks and try again when the fix has been deployed.

the new release is out

**Comment by nelson-liu** [comment]
I'm still seeing this, but weirdly enough only on the codalab public instances (if I run the bundle on my own worker, it works fine). I have a pair of bundles that use the docker same docker image / hash, but one fails with "Unable to find image" and the other works just fine.

Happy to share more details, the bundles are private at the moment.

I wonder if it's something about the host itself, given that all the failures are happening on the codalab public instances...maybe this is just a buggy error message for when the host is out of disk space for pulling the docker images?
