### ISSUE TITLE
[USER ISSUE] Missing 'created' field when running competitiond.py

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#2488]
**Describe the bug**
Running competitiond.py for SQuAD 2.0 exits with an error saying that the 'created' key is not present on some metadata.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0x816632b5306d41d3ba80ccecc84f1b6e
- *UUID of problem bundle (please don't delete)*: n/a
- *Error message received from Codalab (if applicable)*: 
[INFO] 2020-06-23 01:15:06,605: Running batch competition evaluation
[DEBUG] 2020-06-23 01:15:07,792: Collecting latest submissions
Traceback (most recent call last):
  File "./scripts/competitiond.py", line 851, in <module>
    main()
  File "./scripts/competitiond.py", line 847, in main
    comp.run_once()
  File "./scripts/competitiond.py", line 728, in run_once
    submissions, num_total_submissions, num_period_submissions = self.collect_submissions()
  File "./scripts/competitiond.py", line 428, in collect_submissions
    ) = self._fetch_submission_history()
  File "./scripts/competitiond.py", line 361, in _fetch_submission_history
    timestamp = eval_bundle['metadata']['created']
KeyError: 'created'

 - *OS (if on CLI)*: Ubuntu 18.04
 - *Codalab CLI Version (if on CLI)*: 0.5.15
 - *Browser (if on Web)*;

**To Reproduce**
Same instructions as https://github.com/codalab/codalab-worksheets/issues/1910

**Comment by candicegjing** [comment]
This is fixed in https://github.com/codalab/codalab-worksheets/pull/2475

**Comment by robinjia** [comment]
Thanks! I pulled the latest version and still got this error. Is that expected? Based on Percy's comment in https://github.com/codalab/codalab-worksheets/issues/2379 it makes sense that the error persists, just wanted to double-check.

**Comment by robinjia** [comment]
In case this is helpful, I found a bundle on the SQuAD 2.0 leaderboard that is missing a created field 0xf01f87e26b1549ac89ad1fb733304bfd

**Comment by nelson-liu** [comment]
I think `competitiond.py` needs a fix too, yeah. The existing change only makes newly-created bundles have a proper "created" field, but those buggy ones that don't can still cause errors.

**Comment by candicegjing** [comment]
@robinjia The server needs to be updated to reflect this fix.

**Comment by candicegjing** [comment]
@robinjia for those bundles that `created` field is already missing, we might not be able to retrieve them back. If that's something critical, the only thing we can do now is to resubmit a new bundle.

**Comment by nelson-liu** [comment]
doesn't the fix only apply to bundle creation? Bundles that currently have a `None` created field will stay that way, right?

**Comment by candicegjing** [comment]
> doesn't the fix only apply to bundle creation? Bundles that currently have a `None` created field will stay that way, right?

That's right.

**Comment by robinjia** [comment]
I see, it seems to be working now that I've removed the bundle with missing `created` field and am regenerating it now. Thanks!
